languageCode = "da-dk"
title = "HLK-noter"
baseurl = "http://hlk.morsby.dk"
theme = "hugo-theme-learn"

ignoreFiles = [ "Icon\\?$", "Icon\\?", "Icon\\r" ]

[params]
  menu = [ "kardiologi", "lungemedicin", "karkirurgi", "thoraxkirurgi", "forelaesning" ]
